namespace Application.Errors;

public enum ErrorCode
{
    AUTH_REGISTRATION_DISABLED,

    AUTH_USERNAME_REQUIRED,
    AUTH_EMAIL_REQUIRED,
    AUTH_PASSWORD_REQUIRED,
    AUTH_PASSWORDS_DO_NOT_MATCH,

    AUTH_EMAIL_ALREADY_REGISTERED,
    AUTH_USERNAME_ALREADY_TAKEN,

    AUTH_ACTIVATION_TOKEN_REQUIRED,
    AUTH_ACTIVATION_TOKEN_INVALID,
    AUTH_ACTIVATION_TOKEN_ALREADY_USED,
    AUTH_ACTIVATION_TOKEN_EXPIRED
}
